AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
Layout/LineLength:
  AutoCorrect: true
  IgnoredPatterns: ['\A*#']
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'Guardfile'
Style/Documentation:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: true
Layout/HashAlignment:
  Enabled: true
Layout/ParameterAlignment:
  Enabled: true
Layout/ClosingParenthesisIndentation:
  Enabled: true
Layout/FirstArgumentIndentation:
  Enabled: true
Layout/FirstArrayElementIndentation:
  Enabled: true
Layout/FirstHashElementIndentation:
  Enabled: true
Layout/FirstParameterIndentation:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashBraceLayout:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true